-- vim.cmd[[ let g:ale_linters = { 'python': ['pylint'] } ]]
-- vim.cmd[[ let g:ale_fixers = { 'python': ['black', 'isort'] } ]]
-- vim.cmd[[ let g:ale_fix_on_save = 1 ]]
-- vim.cmd[[ let g:ale_disable_lsp = 1 ]]
